### ISSUE TITLE
Wondering how the repo used?

### ISSUE THREAD

**Issue by Whohahaha** [Xeler-ync/SZTU-ZDPJ#1]
又要评教了，讲讲这工具咋用的呗？我跑了很久然后在`    driver = webdriver.Chrome(options=options)`卡住了，请问应当进行什么调整？

**Comment by Xeler-ync** [comment]
> 又要评教了，讲讲这工具咋用的呗？我跑了很久然后在` driver = webdriver.Chrome(options=options)`卡住了，请问应当进行什么调整？

## 使用方式
需要一个 `seleniums` 和 `chromewebdriver`

在根目录新建一个 `xh_pass.json`
内容如下
```
{
    "xuehao": "your_xue_hao_here",
    "password": "your_password_here"
}
```
然后运行
```
python3 SZTU-ZDPJ.py
```

注：使用完之后建议手动检查评教是否全部成功
有需要可以调整 [每个评教的 `Xpath` 起始点](https://github.com/Xeler-ync/SZTU-ZDPJ/blob/main/SZTU-ZDPJ.py#L17) 与 [ `Xpath` 间隔](https://github.com/Xeler-ync/SZTU-ZDPJ/blob/main/SZTU-ZDPJ.py#L22)

## 对于你遇到的问题
看一下有无报错，有可能是缺少 `chromewebdriver` ，可以来 [这里](https://chromedriver.chromium.org/downloads) 下载，注意版本应当与你的 `chrome` 对应

**Comment by Whohahaha** [comment]
感谢回复，我已经完成了评教，并且基于您的库对于今年的系统进行了适配，并且发布了我自己的fork，再次感激，祝一切顺利。
