### ISSUE TITLE
在登录的时候，网站加入了验证码验证，似乎不可用了

### ISSUE THREAD

**Issue by shadow-aaa** [Xeler-ync/SZTU-ZDPJ#3]
填完密码后会要求输入验证码

**Comment by Xeler-ync** [comment]
> 填完密码后会要求输入验证码

学校统一认证平台更新了，登录教务系统需要身份认证，使用的是在入学时在教务系统留存的手机号码。
具体通知可以参考年级群，或者联系 [我](xeler.ync@gmail.com) ，我给你发通知原文。

可以先把 [这里](https://github.com/Xeler-ync/SZTU-ZDPJ/blob/3daed8289d77ee050d404e475cc7f8bde813d4a6/SZTU-ZDPJ.py#L86) 的延迟改长一点，如何手动操作 selenium 页面处理验证码。

ps：我在外面实习，你发 issue 我才知道要评教了（乐）

**Comment by shadow-aaa** [comment]
okok，下次评教我试试

**Comment by Xeler-ync** [comment]
加上了
[ver1.2](https://github.com/Xeler-ync/SZTU-ZDPJ/releases/tag/ver1.2)

**Comment by shadow-aaa** [comment]
👍
